# Generated by Django 3.2.6 on 2021-08-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_webpushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='p256dh',
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='subscription',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
