# Generated by Django 4.2.14 on 2024-08-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.TextField(choices=[('user', '站内信'), ('reply', '评论回复'), ('mention', '提及我的'), ('like', '收到的赞'), ('system', '系统通知')], default='system'),
        ),
    ]
