# Generated by Django 4.2.14 on 2024-08-22 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_alter_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='common_mess_sender__bc7b10_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='common_mess_receive_90b6da_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.chat'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['sender'], name='common_chat_sender__a87097_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['receiver'], name='common_chat_receive_e03de1_idx'),
        ),
    ]
