# Generated by Django 4.2.14 on 2024-08-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_chat_remove_message_common_mess_sender__bc7b10_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.chat'),
        ),
    ]
