# Generated by Django 4.2.14 on 2024-08-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_message_chat_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='common_chat_sender__a87097_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='common_chat_receive_e03de1_idx',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('sender__lt', models.F('receiver'))), fields=('sender', 'receiver'), name='unique_chat_pair'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('receiver__lt', models.F('sender'))), fields=('receiver', 'sender'), name='unique_chat_pair_reverse'),
        ),
    ]
