# Generated by Django 4.2.14 on 2024-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_chat_common_chat_sender__a87097_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_chat_pair',
        ),
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_chat_pair_reverse',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_chat_pair'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('receiver', 'sender'), name='unique_chat_pair_reverse'),
        ),
    ]
