# Generated by Django 4.2.14 on 2024-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_chat_unique_chat_pair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.TextField(choices=[('user', '站内信'), ('reply', '评论回复'), ('mention', '提及我的'), ('like', '收到的赞'), ('system', '系统通知')], default='system'),
        ),
    ]
