# Generated by Django 4.2.14 on 2024-09-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_message_type_chat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='type',
            new_name='classify',
        ),
    ]
