# Generated by Django 4.2.14 on 2024-09-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_rename_message_chatmessage_chat_last_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlike',
            name='dislike_latest_user',
        ),
        migrations.RemoveField(
            model_name='chatlike',
            name='like_latest_user',
        ),
        migrations.AddField(
            model_name='chatlike',
            name='latest_like_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
