# Generated by Django 4.2.14 on 2024-09-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_chat_unique_chat_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
