# Generated by Django 4.2.14 on 2024-09-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_chatmessage_common_chat_chat_it_5599fc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
