# Generated by Django 4.2.14 on 2024-10-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0026_alter_review_pinyin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0019_rename_raw_post_chatlike_raw_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlike',
            name='raw_post_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_assessment.course'),
        ),
        migrations.AlterField(
            model_name='chatlike',
            name='raw_post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chatlike',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
