# Generated by Django 4.2.14 on 2024-10-15 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0026_alter_review_pinyin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0020_alter_chatlike_raw_post_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatreply',
            old_name='raw_post',
            new_name='raw_post_id',
        ),
        migrations.RenameField(
            model_name='chatreply',
            old_name='content',
            new_name='reply_content',
        ),
        migrations.AddField(
            model_name='chatreply',
            name='raw_post_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatreply',
            name='raw_post_course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course_assessment.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatreply',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reply_notice_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatreply',
            name='unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatlike',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_notice_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatreply',
            name='raw_post_classify',
            field=models.CharField(choices=[('review', '关于评价的回复'), ('reply', '楼中楼的回复')]),
        ),
    ]
