# Generated by Django 4.2.14 on 2024-10-17 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0021_rename_raw_post_chatreply_raw_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='unread_count',
            new_name='receiver_unread_count',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
