# Generated by Django 4.2.14 on 2024-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_chatmessage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlike',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_by'], name='common_chat_created_721032_idx'),
        ),
    ]
