# Generated by Django 4.2.14 on 2025-01-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_remove_chatreply_unread_chatlike_chat_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('file', 'File'), ('img', 'Image')], default='file'),
        ),
    ]
