# Generated by Django 4.2.14 on 2025-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_uploadedfile_file_size_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
