# Generated by Django 4.2.14 on 2025-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_uploadedfile_ref_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
