# Generated by Django 4.2.14 on 2025-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_alter_uploadedfile_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
