# Generated by Django 4.2.14 on 2025-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_about_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
