# Generated by Django 4.2.14 on 2025-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='type',
            field=models.TextField(choices=[('about', '关于'), ('blogs', '博文')], default='about'),
        ),
    ]
