# Generated by Django 4.2.30 on 2026-09-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_resource_file_management_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccessRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048, unique=True)),
                ('mode', models.CharField(choices=[('login', '登录用户'), ('admin', '资料管理员')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('path', models.TextField(blank=True)),
                ('destination', models.TextField(blank=True)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDownloadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('path', models.TextField()),
                ('authenticated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
