# Generated by Django 4.2.30 on 2026-09-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_resource_management_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedownloadevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcedownloadevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='resourcedownloadevent',
            name='user_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcedownloadevent',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
