# Generated by Django 4.2.30 on 2026-09-28 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0046_resourcenotificationoutbox_result_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=64)),
                ('manifest', models.JSONField(default=list)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('source_bytes', models.BigIntegerField(default=0)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('zip_bytes', models.BigIntegerField(default=0)),
                ('processed_bytes', models.BigIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('creator', models.CharField(db_index=True, max_length=64)),
                ('ip_digest', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(db_index=True, null=True)),
                ('message', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceArchiveNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('freed_bytes', models.BigIntegerField(default=0)),
                ('reason', models.CharField(max_length=300)),
                ('available_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceArchiveState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceArchiveReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(db_index=True, max_length=64)),
                ('browser', models.CharField(db_index=True, max_length=64)),
                ('request_key', models.UUIDField()),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='common.resourcearchive')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='resourcearchive',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'ready'])), fields=('cache_key',), name='unique_live_resource_archive'),
        ),
        migrations.AddConstraint(
            model_name='resourcearchivereceipt',
            constraint=models.UniqueConstraint(fields=('actor', 'request_key'), name='unique_archive_request'),
        ),
    ]
