# Generated by Django 3.1.4 on 2020-12-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201228_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='created_by',
        ),
    ]
