# Generated by Django 3.1.4 on 2020-12-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0003_remove_school_created_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('course', 'created_by'), name='unique_review'),
        ),
    ]

    replaces = [('core', '0004_auto_20201229_0459')]
