# Generated by Django 3.2 on 2021-04-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0005_app_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classification',
            field=models.TextField(choices=[('general', '通识'), ('pe', '体育'), ('english', '英语'), ('professional', '专业课'), ('politics', '政治')], verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.school', verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.school', verbose_name='院系'),
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
