# Generated by Django 4.0.3 on 2022-03-28 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_courses(apps, schema_editor):
    Course = apps.get_model('course_assessment', 'Course')

    for c in Course.objects.all():
        c.teachers.add(c.teacher)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_assessment', '0008_auto_20210618_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semeseter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=0, max_length=30, verbose_name='课程号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='课程难度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='给分高低'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='homework',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='作业多少'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='review',
            name='reward',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='收获多少'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(default='user', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='course',
            name='classification',
            field=models.TextField(choices=[('general', '通识'), ('pe', '体育'), ('english', '英语'), ('professional', '专业课'), ('politics', '政治'), ('required', '必修'), ('optional', '选修')], verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_assessment.school', verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(to='course_assessment.semeseter', verbose_name='开课学期'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(db_index=True, related_name='books', to='course_assessment.teacher'),
        ),
        migrations.RunPython(migrate_courses),
    ]
