# Generated by Django 4.0.3 on 2022-04-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0010_remove_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], verbose_name='课程难度'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '超好'), (2, '一般'), (3, '杀手')], verbose_name='给分高低'),
        ),
        migrations.AlterField(
            model_name='review',
            name='homework',
            field=models.PositiveSmallIntegerField(choices=[(1, '不多'), (2, '中等'), (3, '超多')], verbose_name='作业多少'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reward',
            field=models.PositiveSmallIntegerField(choices=[(1, '很多'), (2, '一般'), (3, '没有')], verbose_name='收获多少'),
        ),
    ]
