# Generated by Django 4.1 on 2022-08-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_assessment",
            "0011_alter_review_difficulty_alter_review_grade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="modify_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ReviewHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_assessment.review",
                    ),
                ),
            ],
        ),
    ]
