# Generated by Django 4.1 on 2022-10-04 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def set_my_defaults(apps, schema_editor):
    Reviews = apps.get_model('course_assessment', 'review')
    # We can't use .save() because the pre-save hook of `auto_now`
    Reviews.objects.all().update(modify_time=models.F("create_time"))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_assessment",
            "0011_alter_review_difficulty_alter_review_grade_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="edited",
            field=models.BooleanField(default=False, verbose_name="已编辑"),
        ),
        migrations.RenameField(
            model_name="review",
            old_name="created_time",
            new_name="create_time",
        ),
        migrations.AddField(
            model_name="review",
            name="modify_time",
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.CreateModel(
            name="ReviewHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_assessment.review",
                    ),
                ),
            ],
        ),
    ]
