# Generated by Django 4.2.14 on 2024-08-08 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_assessment', '0012_review_modify_time_reviewhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='like',
            new_name='like_count',
        ),
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0.0, null=True, verbose_name='平均评分'),
        ),
        migrations.AddField(
            model_name='course',
            name='normalized_rating',
            field=models.FloatField(default=0.0, null=True, verbose_name='归一化平均评分'),
        ),
        migrations.AddField(
            model_name='review',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='点踩'),
        ),
        migrations.AddField(
            model_name='review',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_assessment.semeseter', verbose_name='开课学期'),
        ),
        migrations.AlterField(
            model_name='semeseter',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='点踩')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAndReplyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('like', models.SmallIntegerField(default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.review')),
                ('review_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_assessment.reviewreply')),
            ],
        ),
    ]
