# Generated by Django 4.2.14 on 2024-08-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0013_rename_course_id_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_assessment.semeseter', verbose_name='开课学期'),
        ),
    ]
