# Generated by Django 4.2.14 on 2024-08-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0014_review_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.semeseter', verbose_name='开课学期'),
        ),
    ]
