# Generated by Django 4.2.14 on 2024-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0015_alter_review_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='平均评分'),
        ),
        migrations.AddField(
            model_name='course',
            name='normalized_rating',
            field=models.FloatField(default=0.0, verbose_name='归一化平均评分'),
        ),
    ]
