# Generated by Django 4.2.14 on 2024-08-23 20:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0016_course_last_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100, verbose_name='拼音'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='course_asse_search__a50c08_gin'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='course_asse_name_f5eff3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['pinyin'], name='course_asse_pinyin_f7d079_idx'),
        ),
    ]
