# Generated by Django 4.2.14 on 2024-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0017_reviewreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
        migrations.AddField(
            model_name='review',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='review',
            name='unlike_count',
            field=models.IntegerField(default=0, verbose_name='点踩'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='unlike_count',
            field=models.IntegerField(default=0, verbose_name='点踩'),
        ),
    ]
