# Generated by Django 4.2.14 on 2024-08-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_assessment', '0018_remove_review_like_review_like_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReplyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.review')),
                ('review_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_assessment.reviewreply')),
            ],
        ),
    ]
