# Generated by Django 4.2.14 on 2024-08-24 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_assessment', '0018_install_extensions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together={('course', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='courselike',
            name='like',
        ),
    ]
