# Generated by Django 4.2.14 on 2024-08-01 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_assessment', '0019_reviewreplylike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewReplyLike',
            new_name='ReviewAndReplyLike',
        ),
    ]
