# Generated by Django 4.2.14 on 2024-08-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0019_alter_courselike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselike',
            name='like',
            field=models.SmallIntegerField(null=True),
        ),
    ]
