# Generated by Django 4.2.14 on 2024-09-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0020_courselike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='children',
            field=models.ManyToManyField(null=True, to='course_assessment.reviewreply'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_parent', to='course_assessment.reviewreply'),
        ),
    ]
