# Generated by Django 4.2.14 on 2024-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course_assessment', '0020_rename_reviewreplylike_reviewandreplylike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewandreplylike',
            name='like',
        ),
        migrations.AddField(
            model_name='reviewandreplylike',
            name='like',
            field=models.SmallIntegerField(default=0, null=True),
            preserve_default=False,
        )
    ]
