# Generated by Django 4.2.14 on 2024-09-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0021_reviewreply_children_reviewreply_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreply',
            name='children',
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='course_assessment.reviewreply'),
        ),
    ]
