# Generated by Django 4.2.14 on 2024-08-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0021_alter_reviewandreplylike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandreplylike',
            name='like',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reviewandreplylike',
            name='review_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_assessment.reviewreply'),
        ),
    ]
