# Generated by Django 4.2.14 on 2024-09-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0022_remove_reviewreply_children_alter_reviewreply_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='评价数量'),
        ),
    ]
