# Generated by Django 4.2.14 on 2024-08-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0022_alter_reviewandreplylike_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='unlike_count',
            new_name='dislike_count',
        ),
        migrations.RenameField(
            model_name='reviewreply',
            old_name='unlike_count',
            new_name='dislike_count',
        ),
    ]
