# Generated by Django 4.2.14 on 2024-09-29 19:08

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0024_course_pinyin_course_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100, verbose_name='拼音'),
        ),
        migrations.AddField(
            model_name='review',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
