# Generated by Django 4.2.14 on 2024-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0025_review_pinyin_review_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pinyin',
            field=models.TextField(blank=True, verbose_name='拼音'),
        ),
    ]
