# Generated by Django 4.2.14 on 2024-11-28 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0026_alter_review_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
