# Generated by Django 4.2.14 on 2025-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_assessment', '0028_remove_review_unique_review_review_unique_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0, null=True, verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dislike_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='不推荐'),
        ),
        migrations.AlterField(
            model_name='course',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='推荐'),
        ),
        migrations.AlterField(
            model_name='course',
            name='normalized_rating',
            field=models.FloatField(db_index=True, default=0.0, null=True, verbose_name='归一化平均评分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='评价数量'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(db_index=True, to='course_assessment.semeseter', verbose_name='开课学期'),
        ),
    ]
