# Generated by Django 4.2.14 on 2024-08-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_cookie_remove_user_cookie_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nwu_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
