# Generated by Django 4.2.14 on 2024-09-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_followed_courses_user_following_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nwu_email',
            new_name='college_email',
        ),
    ]
