# Generated by Django 4.2.14 on 2025-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_college_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_reply',
            field=models.IntegerField(choices=[(0, '允许所有人'), (1, '允许登录用户'), (2, '禁止所有人')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='private_review',
            field=models.IntegerField(choices=[(0, '允许所有人'), (1, '允许登录用户'), (2, '禁止所有人')], default=0),
        ),
    ]
