# Generated by Django 4.2.14 on 2025-01-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_college_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_reply',
            field=models.CharField(choices=[('0', '允许所有人'), ('1', '允许登录用户'), ('2', '禁止所有人')], default='false'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_review',
            field=models.CharField(choices=[('0', '允许所有人'), ('1', '允许登录用户'), ('2', '禁止所有人')], default='false'),
        ),
    ]
